namespace Agrumy.MqttCredentialSync
{
    /// One row of what the sync needs from the device table - ApiId/ApiKey become the MQTT username/password, DeviceId+TenantId scope the ACL to that device's own topic tree.
    public sealed record MqttDeviceCredential(int DeviceId, string ApiId, string ApiKey, int? TenantId);

    /// Builds Mosquitto's acl_file content - one user block per device, restricted to exactly the topic tree that device's own ApiId can already reach over HTTP, nothing broader.
    public static class MosquittoAclBuilder
    {
        /// Topic root must match MqttCommandPublisher.MqttCommandTopic.ForDevice (Agrumy.Api) and MqttController.cpp's publish/subscribe topics (AgrumyFirmware) - "agrumy/{tenantId ?? 0}/{deviceId}/...".
        public static string BuildAclFile(IEnumerable<MqttDeviceCredential> devices)
        {
            var sb = new System.Text.StringBuilder();
            sb.AppendLine("# Generated by Agrumy.MqttCredentialSync - do not edit by hand, overwritten on the next sync.");
            foreach (MqttDeviceCredential device in devices.OrderBy(d => d.ApiId, StringComparer.Ordinal))
            {
                sb.AppendLine();
                sb.AppendLine($"user {device.ApiId}");
                sb.AppendLine($"topic readwrite agrumy/{device.TenantId ?? 0}/{device.DeviceId}/#");
            }
            return sb.ToString();
        }
    }
}
