using Agrumy.MqttCredentialSync;

namespace Agrumy.Api.Tests;

public class MosquittoAclBuilderTests
{
    [Fact]
    public void BuildAclFile_EmptyInput_HeaderOnly()
    {
        string acl = MosquittoAclBuilder.BuildAclFile([]);

        Assert.Contains("Generated by Agrumy.MqttCredentialSync", acl);
        Assert.DoesNotContain("user ", acl);
        Assert.DoesNotContain("topic ", acl);
    }

    [Fact]
    public void BuildAclFile_OneDevice_ScopedToItsOwnTenantAndDeviceId()
    {
        string acl = MosquittoAclBuilder.BuildAclFile([new MqttDeviceCredential(42, "device-api-id", "secret", TenantId: 7)]);

        Assert.Contains("user device-api-id", acl);
        Assert.Contains("topic readwrite agrumy/7/42/#", acl);
    }

    [Fact]
    public void BuildAclFile_NullTenant_FallsBackToZero()
    {
        string acl = MosquittoAclBuilder.BuildAclFile([new MqttDeviceCredential(5, "unassigned-device", "secret", TenantId: null)]);

        Assert.Contains("topic readwrite agrumy/0/5/#", acl);
    }

    [Fact]
    public void BuildAclFile_MultipleDevices_EachGetsItsOwnBlock_NeverReferencingAnotherDevicesId()
    {
        string acl = MosquittoAclBuilder.BuildAclFile(
        [
            new MqttDeviceCredential(1, "device-a", "secret-a", TenantId: 1),
            new MqttDeviceCredential(2, "device-b", "secret-b", TenantId: 1),
        ]);

        Assert.Contains("user device-a", acl);
        Assert.Contains("topic readwrite agrumy/1/1/#", acl);
        Assert.Contains("user device-b", acl);
        Assert.Contains("topic readwrite agrumy/1/2/#", acl);

        // Each block only ever grants its own deviceId - never both under one user.
        int deviceABlockStart = acl.IndexOf("user device-a", StringComparison.Ordinal);
        int deviceBBlockStart = acl.IndexOf("user device-b", StringComparison.Ordinal);
        string deviceABlock = acl[deviceABlockStart..deviceBBlockStart];
        Assert.DoesNotContain("agrumy/1/2/#", deviceABlock);
    }

    [Fact]
    public void BuildAclFile_IsDeterministic_OrderedByApiId()
    {
        var devices = new[]
        {
            new MqttDeviceCredential(2, "zzz-device", "secret", TenantId: 1),
            new MqttDeviceCredential(1, "aaa-device", "secret", TenantId: 1),
        };

        string acl = MosquittoAclBuilder.BuildAclFile(devices);

        Assert.True(acl.IndexOf("aaa-device", StringComparison.Ordinal) < acl.IndexOf("zzz-device", StringComparison.Ordinal));
    }
}
