// <auto-generated />
using System;
using Agrumy.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Agrumy.Api.Migrations.MySql.Migrations
{
    [DbContext(typeof(AgrumyDbContext))]
    [Migration("20260908191945_AddDeviceFarmUnitZoneRuleSimulationSessionID")]
    partial class AddDeviceFarmUnitZoneRuleSimulationSessionID
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Agrumy.Dal.Entities.AuditLogRow", b =>
                {
                    b.Property<int>("IDAuditLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDAuditLog"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ActorEmail")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ActorUserID")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasColumnType("longtext");

                    b.Property<string>("TargetId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TargetType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("TenantID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IDAuditLog");

                    b.HasIndex("TenantID", "TimestampUtc")
                        .HasDatabaseName("ix_auditLog_tenant_timestamp");

                    b.ToTable("auditLog", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.ControllerDataRow", b =>
                {
                    b.Property<int>("IDControllerData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDControllerData"));

                    b.Property<DateTimeOffset?>("DateChanged")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeviceID")
                        .HasColumnType("int");

                    b.Property<bool>("IsOn")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RelayFunction")
                        .HasColumnType("int");

                    b.Property<int>("TenantID")
                        .HasColumnType("int");

                    b.HasKey("IDControllerData");

                    b.HasIndex("DeviceID", "RelayFunction")
                        .IsUnique()
                        .HasDatabaseName("ux_dataController_device_relayFunction");

                    b.ToTable("dataController", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceCommandRow", b =>
                {
                    b.Property<int>("IDDeviceCommand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDDeviceCommand"));

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<int?>("ActiveKey")
                        .HasColumnType("int");

                    b.Property<int>("DeviceID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ExecutedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Payload")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("IDDeviceCommand");

                    b.HasIndex("DeviceID", "ActiveKey")
                        .IsUnique()
                        .HasDatabaseName("ux_deviceCommand_device_activekey");

                    b.HasIndex("DeviceID", "Status")
                        .HasDatabaseName("ix_deviceCommand_device_status");

                    b.ToTable("deviceCommand", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceConfigControllerRelayRow", b =>
                {
                    b.Property<int>("IDDeviceConfigController")
                        .HasColumnType("int");

                    b.Property<int>("Slot")
                        .HasColumnType("int");

                    b.Property<int>("RelayFunction")
                        .HasColumnType("int");

                    b.HasKey("IDDeviceConfigController", "Slot");

                    b.HasIndex("RelayFunction");

                    b.ToTable("deviceConfigControllerRelay", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceConfigControllerRow", b =>
                {
                    b.Property<int>("IDDeviceConfigController")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDDeviceConfigController"));

                    b.Property<int?>("HeatingInterval")
                        .HasColumnType("int");

                    b.Property<bool?>("HeatingIntervalEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("HeatingIntervalLength")
                        .HasColumnType("int");

                    b.Property<double?>("HumidHigh")
                        .HasColumnType("double");

                    b.Property<double?>("HumidLow")
                        .HasColumnType("double");

                    b.Property<double?>("HumidityHysteresis")
                        .HasColumnType("double");

                    b.Property<double?>("LightHigh")
                        .HasColumnType("double");

                    b.Property<double?>("LightHysteresis")
                        .HasColumnType("double");

                    b.Property<int?>("LightInterval")
                        .HasColumnType("int");

                    b.Property<bool?>("LightIntervalEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LightIntervalLength")
                        .HasColumnType("int");

                    b.Property<double?>("LightLow")
                        .HasColumnType("double");

                    b.Property<double?>("MoistHigh")
                        .HasColumnType("double");

                    b.Property<double?>("MoistLow")
                        .HasColumnType("double");

                    b.Property<bool?>("RelayEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<double?>("TempHigh")
                        .HasColumnType("double");

                    b.Property<double?>("TempLow")
                        .HasColumnType("double");

                    b.Property<double?>("TemperatureHysteresis")
                        .HasColumnType("double");

                    b.Property<int?>("VentilationInterval")
                        .HasColumnType("int");

                    b.Property<bool?>("VentilationIntervalEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("VentilationIntervalLength")
                        .HasColumnType("int");

                    b.Property<double?>("WaterHigh")
                        .HasColumnType("double");

                    b.Property<double?>("WaterLevelHysteresis")
                        .HasColumnType("double");

                    b.Property<double?>("WaterLow")
                        .HasColumnType("double");

                    b.Property<int?>("WaterPumpCooldownSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("WaterPumpInterval")
                        .HasColumnType("int");

                    b.Property<bool?>("WaterPumpIntervalEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("WaterPumpIntervalLength")
                        .HasColumnType("int");

                    b.Property<int?>("WaterPumpMaxRunSeconds")
                        .HasColumnType("int");

                    b.HasKey("IDDeviceConfigController");

                    b.ToTable("deviceConfigController", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceConfigSensorRow", b =>
                {
                    b.Property<int>("IDDeviceConfigSensor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDDeviceConfigSensor"));

                    b.Property<double?>("BatteryDividerR1")
                        .HasColumnType("double");

                    b.Property<double?>("BatteryDividerR2")
                        .HasColumnType("double");

                    b.Property<double?>("EcCalibrationOffset")
                        .HasColumnType("double");

                    b.Property<double?>("EcCalibrationSlope")
                        .HasColumnType("double");

                    b.Property<int?>("SensorBarometer")
                        .HasColumnType("int");

                    b.Property<int?>("SensorBattery")
                        .HasColumnType("int");

                    b.Property<int?>("SensorCo2")
                        .HasColumnType("int");

                    b.Property<int?>("SensorEc")
                        .HasColumnType("int");

                    b.Property<int?>("SensorHumid")
                        .HasColumnType("int");

                    b.Property<int?>("SensorLight")
                        .HasColumnType("int");

                    b.Property<int?>("SensorMoist")
                        .HasColumnType("int");

                    b.Property<int?>("SensorPH")
                        .HasColumnType("int");

                    b.Property<int?>("SensorRainLevel")
                        .HasColumnType("int");

                    b.Property<int?>("SensorTemp")
                        .HasColumnType("int");

                    b.Property<int?>("SensorTempSoil")
                        .HasColumnType("int");

                    b.Property<int?>("SensorTvoc")
                        .HasColumnType("int");

                    b.Property<int?>("SensorWaterLevel")
                        .HasColumnType("int");

                    b.Property<int?>("SensorWeight")
                        .HasColumnType("int");

                    b.Property<int?>("SensorWind")
                        .HasColumnType("int");

                    b.Property<double?>("WeightCalibrationFactor")
                        .HasColumnType("double");

                    b.Property<long?>("WeightTareOffset")
                        .HasColumnType("bigint");

                    b.HasKey("IDDeviceConfigSensor");

                    b.HasIndex("SensorBarometer");

                    b.HasIndex("SensorBattery");

                    b.HasIndex("SensorCo2");

                    b.HasIndex("SensorEc");

                    b.HasIndex("SensorHumid");

                    b.HasIndex("SensorLight");

                    b.HasIndex("SensorMoist");

                    b.HasIndex("SensorPH");

                    b.HasIndex("SensorRainLevel");

                    b.HasIndex("SensorTemp");

                    b.HasIndex("SensorTempSoil");

                    b.HasIndex("SensorTvoc");

                    b.HasIndex("SensorWaterLevel");

                    b.HasIndex("SensorWeight");

                    b.HasIndex("SensorWind");

                    b.ToTable("deviceConfigSensor", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceDiagnosticRow", b =>
                {
                    b.Property<int>("DeviceID")
                        .HasColumnType("int");

                    b.Property<string>("Board")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int?>("DeviceTypeID")
                        .HasColumnType("int");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long?>("FreeHeapBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("LowBatteryNotifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("OfflineNotifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("RssiDbm")
                        .HasColumnType("int");

                    b.Property<int?>("TenantID")
                        .HasColumnType("int");

                    b.Property<long?>("UptimeSeconds")
                        .HasColumnType("bigint");

                    b.HasKey("DeviceID");

                    b.HasIndex("DeviceTypeID");

                    b.ToTable("deviceDiagnostic", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceDiscoveryReportRow", b =>
                {
                    b.Property<int>("IDReport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDReport"));

                    b.Property<DateTimeOffset>("DateReported")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DiscoveredApMac")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("Rssi")
                        .HasColumnType("int");

                    b.Property<int>("ScanningDeviceID")
                        .HasColumnType("int");

                    b.HasKey("IDReport");

                    b.HasIndex("DiscoveredApMac")
                        .HasDatabaseName("ix_deviceDiscoveryReport_apMac");

                    b.HasIndex("ScanningDeviceID");

                    b.ToTable("deviceDiscoveryReport", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceFarmRow", b =>
                {
                    b.Property<int>("IDDeviceFarm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDDeviceFarm"));

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceFarmName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Purged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("PurgedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("TenantID")
                        .HasColumnType("int");

                    b.HasKey("IDDeviceFarm");

                    b.ToTable("deviceFarm", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceFarmUnitRow", b =>
                {
                    b.Property<int>("IDDeviceFarmUnit")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeviceFarmID")
                        .HasColumnType("int");

                    b.Property<string>("DeviceFarmUnitName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("TenantID")
                        .HasColumnType("int");

                    b.Property<bool?>("ZoneEnabled")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IDDeviceFarmUnit");

                    b.HasIndex("DeviceFarmID");

                    b.ToTable("deviceFarmUnit", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceFarmUnitZoneRow", b =>
                {
                    b.Property<int>("IDDeviceFarmUnitZone")
                        .HasColumnType("int");

                    b.Property<string>("DashboardWidgetsJson")
                        .HasColumnType("longtext");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeviceFarmUnitID")
                        .HasColumnType("int");

                    b.Property<string>("DeviceFarmUnitZoneName")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int?>("HeatingMaxRunSeconds")
                        .HasColumnType("int");

                    b.Property<bool>("SkipWaterPumpWhenRainPredicted")
                        .HasColumnType("tinyint(1)");

                    b.Property<double?>("TankCapacityLiters")
                        .HasColumnType("double");

                    b.Property<DateTimeOffset?>("TankRefillNotifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("TenantID")
                        .HasColumnType("int");

                    b.Property<int?>("VentilationMaxRunSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("WaterLevelRawEmpty")
                        .HasColumnType("int");

                    b.Property<int?>("WaterLevelRawFull")
                        .HasColumnType("int");

                    b.Property<int?>("WaterPumpCooldownSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("WaterPumpMaxRunSeconds")
                        .HasColumnType("int");

                    b.Property<double?>("WaterPumpMinLevel")
                        .HasColumnType("double");

                    b.HasKey("IDDeviceFarmUnitZone");

                    b.HasIndex("DeviceFarmUnitID");

                    b.ToTable("deviceFarmUnitZone", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceFarmUnitZoneRuleRow", b =>
                {
                    b.Property<int>("IDDeviceFarmUnitZoneRule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDDeviceFarmUnitZoneRule"));

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("DeviceFarmID")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceFarmUnitID")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceFarmUnitZoneID")
                        .HasColumnType("int");

                    b.Property<bool>("IsSafetyRule")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NotificationBody")
                        .HasColumnType("longtext");

                    b.Property<string>("NotificationSubject")
                        .HasColumnType("longtext");

                    b.Property<int?>("RelayFunction")
                        .HasColumnType("int");

                    b.Property<string>("RootConditionJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SimulationSessionID")
                        .HasColumnType("int");

                    b.Property<int>("TenantID")
                        .HasColumnType("int");

                    b.HasKey("IDDeviceFarmUnitZoneRule");

                    b.HasIndex("DeviceFarmID")
                        .HasDatabaseName("ix_deviceFarmUnitZoneRule_farm");

                    b.HasIndex("DeviceFarmUnitID")
                        .HasDatabaseName("ix_deviceFarmUnitZoneRule_unit");

                    b.HasIndex("DeviceFarmUnitZoneID")
                        .HasDatabaseName("ix_deviceFarmUnitZoneRule_zone");

                    b.HasIndex("SimulationSessionID")
                        .HasDatabaseName("ix_deviceFarmUnitZoneRule_simulationSession");

                    b.HasIndex("TenantID")
                        .HasDatabaseName("ix_deviceFarmUnitZoneRule_tenant");

                    b.ToTable("deviceFarmUnitZoneRule", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceFirmwareRow", b =>
                {
                    b.Property<int>("IDDeviceFirmware")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDDeviceFirmware"));

                    b.Property<string>("Board")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTimeOffset?>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DeviceTypeID")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("FullImageFileName")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("FullImageSha256")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long?>("FullImageSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FullImageUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IDDeviceFirmware");

                    b.HasIndex("Board", "Source")
                        .HasDatabaseName("ix_deviceFirmware_board_source");

                    b.ToTable("deviceFirmware", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceManualOverrideRow", b =>
                {
                    b.Property<int>("IDDeviceManualOverride")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDDeviceManualOverride"));

                    b.Property<int>("DeviceID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<int>("RelayFunction")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("TargetHysteresis")
                        .HasColumnType("double");

                    b.Property<int?>("TargetMetric")
                        .HasColumnType("int");

                    b.Property<double?>("TargetThreshold")
                        .HasColumnType("double");

                    b.Property<int>("TenantID")
                        .HasColumnType("int");

                    b.HasKey("IDDeviceManualOverride");

                    b.HasIndex("DeviceID", "RelayFunction")
                        .IsUnique()
                        .HasDatabaseName("ux_deviceManualOverride_device_relayfunction");

                    b.ToTable("deviceManualOverride", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceRoleRow", b =>
                {
                    b.Property<int>("IDDeviceRole")
                        .HasColumnType("int");

                    b.Property<bool?>("ControllerEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DeviceRoleName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("SensorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IDDeviceRole");

                    b.ToTable("deviceRole", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceRow", b =>
                {
                    b.Property<int>("IDDevice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDDevice"));

                    b.Property<string>("ApiId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool?>("BatteryEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CommandVersion")
                        .HasColumnType("int");

                    b.Property<int?>("ConfigVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("Debug")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeviceConfigControllerID")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceConfigSensorID")
                        .HasColumnType("int");

                    b.Property<bool?>("DeviceControllerEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("DeviceFarmUnitID")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceFarmUnitZoneID")
                        .HasColumnType("int");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int?>("DeviceRoleID")
                        .HasColumnType("int");

                    b.Property<bool?>("DeviceSensorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("DeviceTypeServiceID")
                        .HasColumnType("int");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirmwareTargetVersion")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool?>("FirmwareUpdate")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("GatewayProfile")
                        .HasColumnType("int");

                    b.Property<bool>("IsGateway")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LastFullConfigSentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("LastSensorDetectionAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastSensorDetectionResult")
                        .HasColumnType("longtext");

                    b.Property<bool?>("LoRaGatewayEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("LoRaLastUplinkCounter")
                        .HasColumnType("bigint");

                    b.Property<string>("LoRaPrivateKeyHex")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("ManualDeviceTypeID")
                        .HasColumnType("int");

                    b.Property<bool>("Purged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("PurgedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("Reboot")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Reset")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ServicePoint")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ServicePublicKey")
                        .HasColumnType("longtext");

                    b.Property<bool?>("SleepDeepEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("SleepSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("TenantID")
                        .HasColumnType("int");

                    b.HasKey("IDDevice");

                    b.HasIndex("ApiId")
                        .IsUnique()
                        .HasDatabaseName("ApiID_UNIQUE");

                    b.HasIndex("DeviceConfigControllerID");

                    b.HasIndex("DeviceConfigSensorID");

                    b.HasIndex("DeviceFarmUnitID");

                    b.HasIndex("DeviceRoleID");

                    b.HasIndex("DeviceTypeServiceID");

                    b.HasIndex("ManualDeviceTypeID");

                    b.HasIndex("TenantID")
                        .HasDatabaseName("ix_device_tenant");

                    b.HasIndex("MacAddress", "TenantID")
                        .IsUnique()
                        .HasDatabaseName("MacAddress_TenantID_UNIQUE");

                    b.ToTable("device", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceScheduleSlotRow", b =>
                {
                    b.Property<int>("IDDeviceScheduleSlot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDDeviceScheduleSlot"));

                    b.Property<int>("DaysOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("DeviceConfigControllerID")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("RelayFunction")
                        .HasColumnType("int");

                    b.Property<int>("Start")
                        .HasColumnType("int");

                    b.HasKey("IDDeviceScheduleSlot");

                    b.HasIndex("DeviceConfigControllerID");

                    b.ToTable("deviceScheduleSlot", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceSimulationRow", b =>
                {
                    b.Property<int>("DeviceID")
                        .HasColumnType("int");

                    b.Property<double?>("Barometer")
                        .HasColumnType("double");

                    b.Property<int?>("Battery")
                        .HasColumnType("int");

                    b.Property<int?>("Co2")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<double?>("Humidity")
                        .HasColumnType("double");

                    b.Property<int?>("Light")
                        .HasColumnType("int");

                    b.Property<double?>("LiquidPH")
                        .HasColumnType("double");

                    b.Property<int?>("Moisture")
                        .HasColumnType("int");

                    b.Property<int?>("RainLevel")
                        .HasColumnType("int");

                    b.Property<double?>("SoilTemperature")
                        .HasColumnType("double");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double");

                    b.Property<int?>("Tvoc")
                        .HasColumnType("int");

                    b.Property<int?>("WaterLevel")
                        .HasColumnType("int");

                    b.Property<int?>("Wind")
                        .HasColumnType("int");

                    b.HasKey("DeviceID");

                    b.ToTable("deviceSimulation", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceTypeRelayRow", b =>
                {
                    b.Property<int>("IDDeviceTypeRelay")
                        .HasColumnType("int");

                    b.Property<string>("RelayName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("IDDeviceTypeRelay");

                    b.ToTable("deviceTypeRelay", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceTypeRow", b =>
                {
                    b.Property<int>("IDDeviceType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDDeviceType"));

                    b.Property<bool>("ControllerCapable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Kit")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PinoutJson")
                        .HasColumnType("longtext");

                    b.HasKey("IDDeviceType");

                    b.HasIndex("Kit")
                        .IsUnique()
                        .HasDatabaseName("ux_deviceType_kit");

                    b.ToTable("deviceType", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceTypeSensorRow", b =>
                {
                    b.Property<int>("IDDeviceTypeSensor")
                        .HasColumnType("int");

                    b.Property<int?>("Barometer")
                        .HasColumnType("int");

                    b.Property<int?>("Battery")
                        .HasColumnType("int");

                    b.Property<int?>("Co2")
                        .HasColumnType("int");

                    b.Property<int?>("Ec")
                        .HasColumnType("int");

                    b.Property<int?>("Humidity")
                        .HasColumnType("int");

                    b.Property<int?>("Light")
                        .HasColumnType("int");

                    b.Property<int?>("Moisture")
                        .HasColumnType("int");

                    b.Property<int?>("RainLevel")
                        .HasColumnType("int");

                    b.Property<string>("SensorDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("SensorName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int?>("Temperature")
                        .HasColumnType("int");

                    b.Property<int?>("TemperatureSoil")
                        .HasColumnType("int");

                    b.Property<int?>("Tvoc")
                        .HasColumnType("int");

                    b.Property<int?>("WaterPH")
                        .HasColumnType("int");

                    b.Property<int?>("WaterTankLevel")
                        .HasColumnType("int");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.Property<int?>("Wind")
                        .HasColumnType("int");

                    b.HasKey("IDDeviceTypeSensor");

                    b.ToTable("deviceTypeSensor", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceTypeServiceRow", b =>
                {
                    b.Property<int>("IDDeviceTypeService")
                        .HasColumnType("int");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.HasKey("IDDeviceTypeService");

                    b.ToTable("deviceTypeService", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceVirtualRow", b =>
                {
                    b.Property<int>("DeviceID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("DeviceID");

                    b.ToTable("deviceVirtual", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.EventDeviceRow", b =>
                {
                    b.Property<int>("IDEventDevice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDEventDevice"));

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeviceID")
                        .HasColumnType("int");

                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<int>("TenantID")
                        .HasColumnType("int");

                    b.HasKey("IDEventDevice");

                    b.HasIndex("EventID");

                    b.HasIndex("DeviceID", "Date")
                        .HasDatabaseName("ix_eventDevice_device_date");

                    b.ToTable("eventDevice", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.EventTypeRow", b =>
                {
                    b.Property<int>("IDEventType")
                        .HasColumnType("int");

                    b.Property<string>("EventTypeName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("IDEventType");

                    b.ToTable("eventType", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.GatewayDeviceMappingRow", b =>
                {
                    b.Property<int>("IDGatewayDeviceMapping")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDGatewayDeviceMapping"));

                    b.Property<DateTimeOffset?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DevEUI")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int>("IDDevice")
                        .HasColumnType("int");

                    b.Property<int>("IDGatewayDevice")
                        .HasColumnType("int");

                    b.HasKey("IDGatewayDeviceMapping");

                    b.HasIndex("IDDevice");

                    b.HasIndex("IDGatewayDevice", "DevEUI")
                        .IsUnique()
                        .HasDatabaseName("ux_gatewayDeviceMapping_gateway_deveui");

                    b.ToTable("gatewayDeviceMapping", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.RefreshTokenRow", b =>
                {
                    b.Property<int>("IDRefreshToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDRefreshToken"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("IDRefreshToken");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("TokenHash_UNIQUE");

                    b.HasIndex("UserID")
                        .HasDatabaseName("ix_userRefreshToken_userID");

                    b.ToTable("userRefreshToken", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.RuleNotificationStateRow", b =>
                {
                    b.Property<int>("IDRuleNotificationState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDRuleNotificationState"));

                    b.Property<int>("DeviceFarmUnitZoneID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastFiredAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RuleID")
                        .HasColumnType("int");

                    b.Property<bool>("WasTrue")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IDRuleNotificationState");

                    b.HasIndex("DeviceFarmUnitZoneID");

                    b.HasIndex("RuleID", "DeviceFarmUnitZoneID")
                        .IsUnique()
                        .HasDatabaseName("ux_ruleNotificationState_rule_zone");

                    b.ToTable("ruleNotificationState", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.SensorDataReportRow", b =>
                {
                    b.Property<int>("IDSensorDataReport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDSensorDataReport"));

                    b.Property<DateTimeOffset?>("DateGenerated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DeviceID")
                        .HasColumnType("int")
                        .HasColumnName("deviceID");

                    b.Property<string>("ReportName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("SensorData")
                        .HasColumnType("longtext")
                        .HasColumnName("sensorData");

                    b.HasKey("IDSensorDataReport");

                    b.HasIndex("DeviceID");

                    b.ToTable("sensorDataReport", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.SensorDataRow", b =>
                {
                    b.Property<int>("IDSensorData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDSensorData"));

                    b.Property<double?>("Barometer")
                        .HasColumnType("double");

                    b.Property<int?>("Battery")
                        .HasColumnType("int");

                    b.Property<int?>("Co2")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeviceFarmUnitID")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceFarmUnitZoneID")
                        .HasColumnType("int");

                    b.Property<int>("DeviceID")
                        .HasColumnType("int");

                    b.Property<double?>("Ec")
                        .HasColumnType("double");

                    b.Property<double?>("Humidity")
                        .HasColumnType("double");

                    b.Property<int?>("Light")
                        .HasColumnType("int");

                    b.Property<double?>("LiquidPH")
                        .HasColumnType("double");

                    b.Property<int?>("Moisture")
                        .HasColumnType("int");

                    b.Property<int?>("RainLevel")
                        .HasColumnType("int");

                    b.Property<double?>("SoilTemperature")
                        .HasColumnType("double");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double");

                    b.Property<int>("TenantID")
                        .HasColumnType("int");

                    b.Property<int?>("Tvoc")
                        .HasColumnType("int");

                    b.Property<int?>("WaterLevel")
                        .HasColumnType("int");

                    b.Property<double?>("Weight")
                        .HasColumnType("double");

                    b.Property<int?>("Wind")
                        .HasColumnType("int");

                    b.HasKey("IDSensorData");

                    b.HasIndex("DeviceFarmUnitID");

                    b.HasIndex("DeviceFarmUnitZoneID", "DateCreated")
                        .HasDatabaseName("ix_dataSensor_deviceFarmUnitZone_date");

                    b.HasIndex("DeviceID", "TenantID", "DateCreated")
                        .HasDatabaseName("ix_dataSensor_device_tenant_date");

                    b.ToTable("dataSensor", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.ServerConfigRow", b =>
                {
                    b.Property<int>("IDServerConfig")
                        .HasColumnType("int");

                    b.Property<int?>("ActivationResendCooldownMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("AllowSelfServiceTenantCreation")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateOnly?>("ArchiveCustomCutoffDate")
                        .HasColumnType("date");

                    b.Property<int?>("ArchiveCustomRollingDays")
                        .HasColumnType("int");

                    b.Property<int>("ArchiveCutoffMode")
                        .HasColumnType("int");

                    b.Property<string>("ArchiveDatabaseName")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("ArchiveEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ArchiveHost")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset?>("ArchiveLastRunAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ArchivePassword")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int?>("ArchivePort")
                        .HasColumnType("int");

                    b.Property<string>("ArchiveUsername")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<double?>("BatteryLowHysteresis")
                        .HasColumnType("double");

                    b.Property<double?>("BatteryLowThreshold")
                        .HasColumnType("double");

                    b.Property<int>("ConfigHeartbeatHours")
                        .HasColumnType("int");

                    b.Property<int>("DevicePinValidMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("EmailFromAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("EmailFromName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmailHost")
                        .HasColumnType("longtext");

                    b.Property<string>("EmailPassword")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int>("EmailPort")
                        .HasColumnType("int");

                    b.Property<bool>("EmailUseStartTls")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("EmailUsername")
                        .HasColumnType("longtext");

                    b.Property<int?>("EventDedupeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("FirmwareCustomRepositoryUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("FirmwareGitHubRepository")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTimeOffset?>("FirmwareLastRefreshedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("FirmwareRefreshIntervalHours")
                        .HasColumnType("int");

                    b.Property<int>("FirmwareSource")
                        .HasColumnType("int");

                    b.Property<bool>("GatewayEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("GatewayMode")
                        .HasColumnType("int");

                    b.Property<int>("GatewayWaitWindowSeconds")
                        .HasColumnType("int");

                    b.Property<double?>("HumidityHysteresis")
                        .HasColumnType("double");

                    b.Property<string>("JWTKey")
                        .HasColumnType("longtext");

                    b.Property<double?>("LightHysteresis")
                        .HasColumnType("double");

                    b.Property<int?>("MaxRulesPerZone")
                        .HasColumnType("int");

                    b.Property<string>("MqttBrokerHost")
                        .HasColumnType("longtext");

                    b.Property<int>("MqttBrokerPort")
                        .HasColumnType("int");

                    b.Property<string>("MqttPassword")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<bool>("MqttTransportEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MqttUsername")
                        .HasColumnType("longtext");

                    b.Property<int>("PasswordMinLength")
                        .HasColumnType("int");

                    b.Property<bool>("PasswordRequireComplexity")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("PortHTTP")
                        .HasColumnType("int");

                    b.Property<int?>("PortHTTPS")
                        .HasColumnType("int");

                    b.Property<bool>("ProblemEventAlertsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ProblemEventExpiryHours")
                        .HasColumnType("int");

                    b.Property<bool>("PurgeOrphanedSensorDataScheduleEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("RecycleBinRetentionDays")
                        .HasColumnType("int");

                    b.Property<int?>("SensorDataRetentionDays")
                        .HasColumnType("int");

                    b.Property<double?>("TankRefillHysteresis")
                        .HasColumnType("double");

                    b.Property<double?>("TankRefillThreshold")
                        .HasColumnType("double");

                    b.Property<double?>("TemperatureHysteresis")
                        .HasColumnType("double");

                    b.Property<bool>("TenantManagementEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<double?>("WaterLevelHysteresis")
                        .HasColumnType("double");

                    b.Property<int?>("WaterPumpCooldownSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("WaterPumpMaxRunSeconds")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("WeatherCheckedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("WeatherLocationLat")
                        .HasColumnType("double");

                    b.Property<double?>("WeatherLocationLon")
                        .HasColumnType("double");

                    b.Property<int?>("WeatherPollIntervalMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("WeatherRainPredicted")
                        .HasColumnType("tinyint(1)");

                    b.Property<double?>("WeatherRainSkipThreshold")
                        .HasColumnType("double");

                    b.HasKey("IDServerConfig");

                    b.ToTable("serverConfig", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.SimulationSessionDeviceRow", b =>
                {
                    b.Property<int>("IDSimulationSession")
                        .HasColumnType("int");

                    b.Property<int>("DeviceID")
                        .HasColumnType("int");

                    b.HasKey("IDSimulationSession", "DeviceID");

                    b.HasIndex("DeviceID");

                    b.ToTable("simulationSessionDevice", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.SimulationSessionRow", b =>
                {
                    b.Property<int>("IDSimulationSession")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDSimulationSession"));

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("StoppedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TenantID")
                        .HasColumnType("int");

                    b.HasKey("IDSimulationSession");

                    b.ToTable("simulationSession", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.TenantQuotaRow", b =>
                {
                    b.Property<int>("IDTenant")
                        .HasColumnType("int");

                    b.Property<bool>("GatewayEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LoRaEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxControllersPerDevice")
                        .HasColumnType("int");

                    b.Property<int>("MaxDataRetentionDays")
                        .HasColumnType("int");

                    b.Property<int>("MaxFarms")
                        .HasColumnType("int");

                    b.Property<int>("MaxSensorsPerDevice")
                        .HasColumnType("int");

                    b.Property<int>("MaxSimulations")
                        .HasColumnType("int");

                    b.Property<int>("MaxUnits")
                        .HasColumnType("int");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("int");

                    b.Property<int>("MaxZones")
                        .HasColumnType("int");

                    b.Property<int>("MinSensorIntervalMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("MqttEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RecycleBinRetentionDays")
                        .HasColumnType("int");

                    b.HasKey("IDTenant");

                    b.ToTable("tenantConfigQuota", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.TenantRow", b =>
                {
                    b.Property<int>("IDTenant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDTenant"));

                    b.Property<DateTimeOffset?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("EmergencyStopActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double");

                    b.Property<int?>("RecycleBinRetentionDays")
                        .HasColumnType("int");

                    b.Property<string>("ScheduleTimeZone")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IDTenant");

                    b.HasIndex("TenantName")
                        .IsUnique()
                        .HasDatabaseName("Name_UNIQUE");

                    b.ToTable("tenant", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.TenantWifiConfigRow", b =>
                {
                    b.Property<int>("IDTenantWifiConfig")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDTenantWifiConfig"));

                    b.Property<DateTimeOffset?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Ssid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("TenantID")
                        .HasColumnType("int");

                    b.HasKey("IDTenantWifiConfig");

                    b.HasIndex("TenantID")
                        .HasDatabaseName("ix_tenantConfigWifi_tenant");

                    b.ToTable("tenantConfigWifi", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.UserRoleRow", b =>
                {
                    b.Property<int>("IDUserRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDUserRole"));

                    b.Property<string>("RoleName")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("IDUserRole");

                    b.ToTable("userRole", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.UserRow", b =>
                {
                    b.Property<int>("IDUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDUser"));

                    b.Property<DateTimeOffset?>("ActivationLastSentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("ActivationTokenExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ActivationTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("BootstrapSecretHash")
                        .HasColumnType("longtext");

                    b.Property<string>("BootstrapSecretSalt")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DevicePin")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<DateTimeOffset?>("DevicePinExpires")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("PwdHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PwdSalt")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("TenantID")
                        .HasColumnType("int");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset?>("TokensValidAfterUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IDUser");

                    b.HasIndex("ActivationTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ActivationTokenHash_UNIQUE");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("email_UNIQUE");

                    b.HasIndex("TenantID")
                        .HasDatabaseName("ix_user_tenant");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("Username_UNIQUE");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.UserUserRoleRow", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("UserRoleID")
                        .HasColumnType("int");

                    b.HasKey("UserID", "UserRoleID");

                    b.HasIndex("UserRoleID");

                    b.ToTable("userUserRole", (string)null);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.ControllerDataRow", b =>
                {
                    b.HasOne("Agrumy.Dal.Entities.DeviceRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceCommandRow", b =>
                {
                    b.HasOne("Agrumy.Dal.Entities.DeviceRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceConfigControllerRelayRow", b =>
                {
                    b.HasOne("Agrumy.Dal.Entities.DeviceConfigControllerRow", null)
                        .WithMany()
                        .HasForeignKey("IDDeviceConfigController")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Agrumy.Dal.Entities.DeviceTypeRelayRow", null)
                        .WithMany()
                        .HasForeignKey("RelayFunction")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceConfigSensorRow", b =>
                {
                    b.HasOne("Agrumy.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorBarometer")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Agrumy.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorBattery")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Agrumy.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorCo2")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Agrumy.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorEc")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Agrumy.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorHumid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Agrumy.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorLight")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Agrumy.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorMoist")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Agrumy.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorPH")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Agrumy.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorRainLevel")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Agrumy.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorTemp")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Agrumy.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorTempSoil")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Agrumy.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorTvoc")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Agrumy.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorWaterLevel")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Agrumy.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorWeight")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Agrumy.Dal.Entities.DeviceTypeSensorRow", null)
                        .WithMany()
                        .HasForeignKey("SensorWind")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceDiagnosticRow", b =>
                {
                    b.HasOne("Agrumy.Dal.Entities.DeviceRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Agrumy.Dal.Entities.DeviceTypeRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceTypeID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceDiscoveryReportRow", b =>
                {
                    b.HasOne("Agrumy.Dal.Entities.DeviceRow", null)
                        .WithMany()
                        .HasForeignKey("ScanningDeviceID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceFarmUnitRow", b =>
                {
                    b.HasOne("Agrumy.Dal.Entities.DeviceFarmRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceFarmID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceFarmUnitZoneRow", b =>
                {
                    b.HasOne("Agrumy.Dal.Entities.DeviceFarmUnitRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceFarmUnitID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceFarmUnitZoneRuleRow", b =>
                {
                    b.HasOne("Agrumy.Dal.Entities.DeviceFarmRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceFarmID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Agrumy.Dal.Entities.DeviceFarmUnitRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceFarmUnitID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Agrumy.Dal.Entities.DeviceFarmUnitZoneRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceFarmUnitZoneID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Agrumy.Dal.Entities.SimulationSessionRow", null)
                        .WithMany()
                        .HasForeignKey("SimulationSessionID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceManualOverrideRow", b =>
                {
                    b.HasOne("Agrumy.Dal.Entities.DeviceRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceRow", b =>
                {
                    b.HasOne("Agrumy.Dal.Entities.DeviceConfigControllerRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceConfigControllerID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Agrumy.Dal.Entities.DeviceConfigSensorRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceConfigSensorID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Agrumy.Dal.Entities.DeviceFarmUnitRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceFarmUnitID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Agrumy.Dal.Entities.DeviceRoleRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceRoleID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Agrumy.Dal.Entities.DeviceTypeServiceRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceTypeServiceID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Agrumy.Dal.Entities.DeviceTypeRow", null)
                        .WithMany()
                        .HasForeignKey("ManualDeviceTypeID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Agrumy.Dal.Entities.TenantRow", null)
                        .WithMany()
                        .HasForeignKey("TenantID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceScheduleSlotRow", b =>
                {
                    b.HasOne("Agrumy.Dal.Entities.DeviceConfigControllerRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceConfigControllerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceSimulationRow", b =>
                {
                    b.HasOne("Agrumy.Dal.Entities.DeviceRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.DeviceVirtualRow", b =>
                {
                    b.HasOne("Agrumy.Dal.Entities.DeviceRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.EventDeviceRow", b =>
                {
                    b.HasOne("Agrumy.Dal.Entities.EventTypeRow", null)
                        .WithMany()
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.GatewayDeviceMappingRow", b =>
                {
                    b.HasOne("Agrumy.Dal.Entities.DeviceRow", null)
                        .WithMany()
                        .HasForeignKey("IDDevice")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Agrumy.Dal.Entities.DeviceRow", null)
                        .WithMany()
                        .HasForeignKey("IDGatewayDevice")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.RefreshTokenRow", b =>
                {
                    b.HasOne("Agrumy.Dal.Entities.UserRow", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.RuleNotificationStateRow", b =>
                {
                    b.HasOne("Agrumy.Dal.Entities.DeviceFarmUnitZoneRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceFarmUnitZoneID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Agrumy.Dal.Entities.DeviceFarmUnitZoneRuleRow", null)
                        .WithMany()
                        .HasForeignKey("RuleID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.SensorDataReportRow", b =>
                {
                    b.HasOne("Agrumy.Dal.Entities.DeviceRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.SensorDataRow", b =>
                {
                    b.HasOne("Agrumy.Dal.Entities.DeviceFarmUnitRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceFarmUnitID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Agrumy.Dal.Entities.DeviceFarmUnitZoneRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceFarmUnitZoneID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Agrumy.Dal.Entities.DeviceRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.SimulationSessionDeviceRow", b =>
                {
                    b.HasOne("Agrumy.Dal.Entities.DeviceRow", null)
                        .WithMany()
                        .HasForeignKey("DeviceID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Agrumy.Dal.Entities.SimulationSessionRow", null)
                        .WithMany()
                        .HasForeignKey("IDSimulationSession")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.TenantQuotaRow", b =>
                {
                    b.HasOne("Agrumy.Dal.Entities.TenantRow", null)
                        .WithOne()
                        .HasForeignKey("Agrumy.Dal.Entities.TenantQuotaRow", "IDTenant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Agrumy.Dal.Entities.UserUserRoleRow", b =>
                {
                    b.HasOne("Agrumy.Dal.Entities.UserRow", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Agrumy.Dal.Entities.UserRoleRow", null)
                        .WithMany()
                        .HasForeignKey("UserRoleID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
